name: covid19_manager
description: covid19 manager for jp

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
    
  flutter_localizations:
    sdk: flutter
    
  cupertino_icons: ^1.0.2
  flutter_riverpod: ^1.0.3
  hexcolor: ^2.0.5
  fl_chart: ^0.40.6
  hooks_riverpod: ^1.0.3
  json_annotation: ^4.4.0
  build_runner: ^2.1.7
  retrofit: ^3.0.1
  dio: ^4.0.4
  freezed_annotation: ^1.1.0
  json_serializable: ^6.1.3
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  freezed: ^1.1.0
  retrofit_generator: ^3.0.1+1

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: menu
      fonts:
        - asset: fonts/menu.ttf
